### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by marcfrederick** [tim-koehler/Helm-Intellisense#52]
There are currently some test failures. Seems like either the expected values or the tested chart have changed since the introduction of those tests.

```diff
  1) Test Utils
       getValuesFromFile:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '{"replicaCount":1,"foo":{"bar":"baz","baz":["foo","bar","baz"]},"image":{"repository":"nginx","tag":"stable","pullPolicy":"IfNotPresent"},"imagePullSecrets":[],"nameOverride":"","fullnameOverride":"","serviceAccount":{"create":true,"name":null},"podSecurityContext":{},"securityContext":{},"service":{"type":"ClusterIP","port":80},"ingress":{"enabled":false,"annotations":{},"hosts":[{"host":"chart-example.local","paths":[]}],"tls":[]},"resources":{},"nodeSelector":{},"tolerations":[],"affinity":{}}'
- '{"replicaCount":1,"foo":{"bar":"baz","baz":["foo","bar","baz"]},"image":{"repository":"nginx","tag":"stable","pullPolicy":"Always"},"imagePullSecrets":[],"nameOverride":"","fullnameOverride":"","serviceAccount":{"create":true,"name":null},"podSecurityContext":{},"securityContext":{},"service":{"type":"ClusterIP","port":80},"ingress":{"enabled":false,"annotations":{},"hosts":[{"host":"chart-example.local","paths":[]}],"tls":[]},"resources":{},"nodeSelector":{},"tolerations":[],"affinity":{}}'
      + expected - actual

      -{"replicaCount":1,"foo":{"bar":"baz","baz":["foo","bar","baz"]},"image":{"repository":"nginx","tag":"stable","pullPolicy":"IfNotPresent"},"imagePullSecrets":[],"nameOverride":"","fullnameOverride":"","serviceAccount":{"create":true,"name":null},"podSecurityContext":{},"securityContext":{},"service":{"type":"ClusterIP","port":80},"ingress":{"enabled":false,"annotations":{},"hosts":[{"host":"chart-example.local","paths":[]}],"tls":[]},"resources":{},"nodeSelector":{},"tolerations":[],"affinity":{}}
      +{"replicaCount":1,"foo":{"bar":"baz","baz":["foo","bar","baz"]},"image":{"repository":"nginx","tag":"stable","pullPolicy":"Always"},"imagePullSecrets":[],"nameOverride":"","fullnameOverride":"","serviceAccount":{"create":true,"name":null},"podSecurityContext":{},"securityContext":{},"service":{"type":"ClusterIP","port":80},"ingress":{"enabled":false,"annotations":{},"hosts":[{"host":"chart-example.local","paths":[]}],"tls":[]},"resources":{},"nodeSelector":{},"tolerations":[],"affinity":{}}
      
  	at Context.<anonymous> (out/test/suite/utils.test.js:50:16)
  	at processImmediate (internal/timers.js:461:21)
  	at process.callbackTrampoline (internal/async_hooks.js:131:14)

/Applications/Visual Studio Code.app/Contents/Resources/app/out/out-vscode/bootstrap-fork.js:166
  2) Test ValuesCompletionItemProvider
       provideCompletionItems() with `.Values.image.`:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '[{"label":"repository","kind":"Field","detail":"nginx"},{"label":"tag","kind":"Field","detail":"stable"},{"label":"pullPolicy","kind":"Field","detail":"IfNotPresent"}]'
- '[{"label":"repository","kind":"Field","detail":"nginx"},{"label":"tag","kind":"Field","detail":"stable"},{"label":"pullPolicy","kind":"Field","detail":"Always"}]'
      + expected - actual

      -[{"label":"repository","kind":"Field","detail":"nginx"},{"label":"tag","kind":"Field","detail":"stable"},{"label":"pullPolicy","kind":"Field","detail":"IfNotPresent"}]
      +[{"label":"repository","kind":"Field","detail":"nginx"},{"label":"tag","kind":"Field","detail":"stable"},{"label":"pullPolicy","kind":"Field","detail":"Always"}]
      
  	at /Users/marcfrederick/src/Helm-Intellisense/out/test/suite/valuesCompletionItemProvider.test.js:36:16
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/suite/valuesCompletionItemProvider.test.js:5:58)
```

**Comment by Dgamblin01** [comment]
Donnieboi420@icloud.com
